language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-25.0.0
        - android-25

        - extra-google-m2repository
        - extra-android-m2repository

        # System image for emulation
        - sys-img-armeabi-v7a-android-21
    licenses:
        - 'android-sdk-license-.+'
script:
    - ./gradlew assemble lint
    - android list targets
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    - ./gradlew connectedCheck
